/**
 * 一键同步静态数据：飞行器 + 封路内嵌 JS
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const root = path.join(__dirname, "..");

function writeJsEmbed(jsonPath, jsPath, globalName) {
  const data = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
  fs.writeFileSync(
    jsPath,
    `/** Auto-generated by npm run build:data */\nwindow.${globalName}=${JSON.stringify(data)};\n`
  );
  console.log(`  ✓ ${path.relative(root, jsPath)}`);
}

console.log("[build:data] 解析飞行器…");
execSync("node scripts/parse-vehicles-3.js", { cwd: root, stdio: "inherit" });

console.log("[build:data] 同步封路…");
try {
  execSync("node scripts/sync-closures.js", { cwd: root, stdio: "inherit" });
} catch (e) {
  console.warn("[build:data] sync-closures 跳过，使用现有 closures.json");
}

writeJsEmbed(
  path.join(root, "data", "closures.json"),
  path.join(root, "data", "closures.js"),
  "CLOSURES_DATA"
);

console.log("[build:data] 完成");
